Feature/api redesign
AkrosAG/Akros-Marketplace pull request #46
Opened 2022-02-25 16:21 UTC by Ayerbe88

API changes and corresponding DB script, backend and front end adaptations.

2022-02-28 08:33 UTC, stefanleminh requested changes
I think the [Zally-Validator](https://github.com/ethlo/zally-maven-plugin) should be installed. Upon installing and running it through, there were quite a few validation issues that must be adressed before merging - At least the MUST-issues (But of course if possible all the issues, we don't want to have any more issues than we need.

2022-03-01 10:00 UTC, Ayerbe88 commented
API has been changed to fix all MUST issues generated by Zally, along with consequent changes in backend and frontend.

2022-03-01 10:50 UTC, stefanleminh commented
In the api.yaml file, required properties (properties that cannot be null in Objects, such as IDs etc) should be defined as such, so the generated client and server stubs will validate accordingly. [Reference](https://stackoverflow.com/questions/45575493/what-does-required-in-openapi-really-mean#:~:text=The%20required%20keyword%20in%20OpenAPI,%22,%20regardless%20of%20its%20value.)

2022-03-01 15:55 UTC, stefanleminh approved these changes

2022-03-01 16:03 UTC, merged